version: 2
updates:
  # npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 10
    assignees:
      - 'd0whc3r'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    target-branch: 'develop'
    versioning-strategy: 'increase'
    # Group updates for better management
    groups:
      # Group all patch updates
      patch-updates:
        patterns:
          - '*'
        update-types:
          - 'patch'
      # Group TypeScript related updates
      typescript:
        patterns:
          - 'typescript'
          - '@types/*'
          - 'tsup'
          - 'tsx'
      # Group testing related updates
      testing:
        patterns:
          - 'vitest'
          - '@vitest/*'
      # Group linting and formatting
      code-quality:
        patterns:
          - 'oxlint'
          - 'prettier'
          - 'husky'
          - 'lint-staged'
      # Group semantic-release related
      release:
        patterns:
          - 'semantic-release'
          - '@semantic-release/*'
          - 'conventional-changelog-*'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 5
    assignees:
      - 'd0whc3r'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'ci-cd'
      - 'dependencies'
      - 'automated'
