name: 'Setup Node.js and pnpm'
description: 'Setup Node.js and pnpm'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ env.PNPM_VERSION || '10' }}

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION || '22' }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
