name: 'Setup Node.js and pnpm'
description: 'Setup Node.js, pnpm, and install dependencies with optimized caching'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '10'
  install-deps:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js with cache
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Get pnpm store directory
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Cache pnpm store
      if: inputs.install-deps == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml', 'package.json', '.pnpmrc', '.npmrc', 'pnpm-workspace.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml', 'package.json') }}
          ${{ runner.os }}-pnpm-store-

    - name: Cache node_modules
      if: inputs.install-deps == 'true'
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml', 'package.json', '.pnpmrc', '.npmrc', 'pnpm-workspace.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml', 'package.json') }}
          ${{ runner.os }}-node-modules-

    - name: Cache TypeScript build info
      if: inputs.install-deps == 'true'
      uses: actions/cache@v4
      with:
        path: |
          *.tsbuildinfo
          tsconfig.tsbuildinfo
        key: ${{ runner.os }}-tsbuildinfo-${{ hashFiles('tsconfig*.json', 'src/**/*.ts') }}
        restore-keys: |
          ${{ runner.os }}-tsbuildinfo-

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        # Always run pnpm install to ensure consistency
        # pnpm is smart enough to skip if nothing changed
        echo "Installing dependencies..."
        pnpm install --frozen-lockfile

        # Verify installation
        if [ ! -d "node_modules" ]; then
          echo "❌ node_modules directory not found after installation"
          exit 1
        fi

        echo "✅ Dependencies installed successfully"
