# =============================================================================
# PNPM Workspace Configuration
# =============================================================================

# Define workspace packages
packages:
  - '.'

minimumReleaseAge: 4320
# minimumReleaseAgeExclude:
# - "@modelcontextprotocol/sdk"
# - "typescript"

networkConcurrency: 3
childConcurrency: 3
lockfile: true
