name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug', 'needs-triage']
assignees: ['d0whc3r']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure MCP client with...
        2. Run command...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: [e.g. macOS 14.0, Windows 11, Ubuntu 22.04]
        - Node.js version: [e.g. 18.17.0]
        - Package version: [e.g. 1.1.0]
        - MCP Client: [e.g. Claude Desktop, Cursor]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant error messages or logs (please sanitize sensitive information)
      placeholder: |
        Paste error logs here...
        (Remember to remove any sensitive information like cookies or tokens)
      render: shell

  - type: textarea
    id: configuration
    attributes:
      label: MCP Configuration
      description: Your MCP client configuration (sanitized)
      placeholder: |
        {
          "mcpServers": {
            "gencat-egipci": {
              "command": "npx",
              "args": ["-y", "@d0whc3r/egipci-mcp@latest"],
              "env": {
                "EGIPCI_COOKIE": "[REDACTED]"
              }
            }
          }
        }
      render: json

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context, screenshots, or information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided steps to reproduce the issue
          required: true
        - label: I have sanitized any sensitive information from logs and configuration
          required: true
