name: 🔒 Security Report
description: Report a security vulnerability (use GitHub Security Advisories for sensitive issues)
title: '[Security]: '
labels: ['security', 'needs-triage']
assignees: ['d0whc3r']

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: For sensitive security vulnerabilities, please use [GitHub Security Advisories](https://github.com/d0whc3r/egipci-mcp/security/advisories/new) instead of this public issue template.

        This template is for non-sensitive security-related issues like:
        - Security best practices suggestions
        - Documentation improvements for security
        - General security questions

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low - General security improvement
        - Medium - Security best practice violation
        - High - Potential security risk (use Security Advisory instead)
        - Critical - Active security vulnerability (use Security Advisory instead)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security concern
      placeholder: |
        Describe the security issue or improvement suggestion...

        For HIGH or CRITICAL issues, please use GitHub Security Advisories instead.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could be the impact of this security issue?
      placeholder: Describe the potential security impact...

  - type: textarea
    id: recommendation
    attributes:
      label: Recommended Solution
      description: What do you recommend to address this issue?
      placeholder: Suggest how this security issue could be resolved...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant security references or documentation
      placeholder: |
        - OWASP guidelines
        - CVE references
        - Security best practices documentation
        - etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Security Checklist
      description: Please confirm the following
      options:
        - label: This is NOT a critical security vulnerability (I would use Security Advisories for that)
          required: true
        - label: I have not included sensitive information in this public issue
          required: true
        - label: I understand this issue will be publicly visible
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        **For sensitive security vulnerabilities:**
        - Use [GitHub Security Advisories](https://github.com/d0whc3r/egipci-mcp/security/advisories/new)
        - Email maintainers if Security Advisories are not available
        - Do NOT create public issues for sensitive vulnerabilities

        **Security Policy**: [SECURITY.md](https://github.com/d0whc3r/egipci-mcp/blob/master/.github/SECURITY.md)
