name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign issues and PRs
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issueNumber = context.issue.number;
            const isIssue = context.eventName === 'issues';
            const isPR = context.eventName === 'pull_request';

            // Auto-assign to maintainer
            const assignee = 'd0whc3r';

            if (isIssue) {
              // Auto-assign issues to maintainer
              await github.rest.issues.addAssignees({
                owner,
                repo,
                issue_number: issueNumber,
                assignees: [assignee]
              });

              // Add needs-triage label to new issues
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: issueNumber,
                labels: ['needs-triage']
              });

              console.log(`Assigned issue #${issueNumber} to ${assignee} and added needs-triage label`);
            }

            if (isPR) {
              // Auto-assign PRs to maintainer for review
              await github.rest.pulls.requestReviewers({
                owner,
                repo,
                pull_number: issueNumber,
                reviewers: [assignee]
              });

              // Add status label to new PRs
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: issueNumber,
                labels: ['status: needs-triage']
              });

              console.log(`Requested review from ${assignee} for PR #${issueNumber} and added status label`);
            }
