name: Label Sync

on:
  push:
    branches: [master]
    paths: ['.github/labels.yml']
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # Weekly on Monday at 3 AM UTC

permissions:
  issues: write
  pull-requests: write

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Sync labels
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
          repository: ${{ github.repository }}
          prune: true
